language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
before_install:
  - openssl aes-256-cbc
    -K $encrypted_cd6f32ab44b3_key
    -iv $encrypted_cd6f32ab44b3_iv
    -in voipms-sms/src/primary/google-services.json.enc
    -out voipms-sms/src/primary/google-services.json
    -d
